# TODO: minimize
FROM golang:1.11
LABEL Maintainer="Soichi Sumi <soichi.sumi@gmail.com>"

ENV GO111MODULE on

ADD . /go/src/github.com/soichisumi/grpc-k8s-sample
WORKDIR /go/src/github.com/soichisumi/grpc-k8s-sample/api

RUN go build -o ./api .

ENTRYPOINT ["./api"]