// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api-pb/types.proto

/*
Package apipb is a generated protocol buffer package.

It is generated from these files:
	api-pb/types.proto

It has these top-level messages:
	User
	AddUserRequest
	AddUserResponse
	GetUserRequest
	GetUserResponse
	LoginRequest
	LoginResponse
	DeleteUserRequest
	DeleteUserResponse
*/
package apipb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import _ "github.com/golang/protobuf/protoc-gen-go/descriptor"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Age  int32  `protobuf:"varint,2,opt,name=age" json:"age,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

type AddUserRequest struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *AddUserRequest) Reset()                    { *m = AddUserRequest{} }
func (m *AddUserRequest) String() string            { return proto.CompactTextString(m) }
func (*AddUserRequest) ProtoMessage()               {}
func (*AddUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AddUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type AddUserResponse struct {
}

func (m *AddUserResponse) Reset()                    { *m = AddUserResponse{} }
func (m *AddUserResponse) String() string            { return proto.CompactTextString(m) }
func (*AddUserResponse) ProtoMessage()               {}
func (*AddUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type GetUserRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
}

func (m *GetUserRequest) Reset()                    { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()               {}
func (*GetUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type GetUserResponse struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *GetUserResponse) Reset()                    { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string            { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()               {}
func (*GetUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type LoginRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *LoginRequest) Reset()                    { *m = LoginRequest{} }
func (m *LoginRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()               {}
func (*LoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *LoginResponse) Reset()                    { *m = LoginResponse{} }
func (m *LoginResponse) String() string            { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()               {}
func (*LoginResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type DeleteUserRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
}

func (m *DeleteUserRequest) Reset()                    { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()               {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *DeleteUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type DeleteUserResponse struct {
}

func (m *DeleteUserResponse) Reset()                    { *m = DeleteUserResponse{} }
func (m *DeleteUserResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteUserResponse) ProtoMessage()               {}
func (*DeleteUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func init() {
	proto.RegisterType((*User)(nil), "apipb.User")
	proto.RegisterType((*AddUserRequest)(nil), "apipb.AddUserRequest")
	proto.RegisterType((*AddUserResponse)(nil), "apipb.AddUserResponse")
	proto.RegisterType((*GetUserRequest)(nil), "apipb.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "apipb.GetUserResponse")
	proto.RegisterType((*LoginRequest)(nil), "apipb.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "apipb.LoginResponse")
	proto.RegisterType((*DeleteUserRequest)(nil), "apipb.DeleteUserRequest")
	proto.RegisterType((*DeleteUserResponse)(nil), "apipb.DeleteUserResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for UserService service

type UserServiceClient interface {
	AddUser(ctx context.Context, in *AddUserRequest, opts ...grpc.CallOption) (*AddUserResponse, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) AddUser(ctx context.Context, in *AddUserRequest, opts ...grpc.CallOption) (*AddUserResponse, error) {
	out := new(AddUserResponse)
	err := grpc.Invoke(ctx, "/apipb.UserService/AddUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := grpc.Invoke(ctx, "/apipb.UserService/GetUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := grpc.Invoke(ctx, "/apipb.UserService/Login", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceServer interface {
	AddUser(context.Context, *AddUserRequest) (*AddUserResponse, error)
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_AddUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).AddUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apipb.UserService/AddUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).AddUser(ctx, req.(*AddUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apipb.UserService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apipb.UserService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "apipb.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddUser",
			Handler:    _UserService_AddUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _UserService_GetUser_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _UserService_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api-pb/types.proto",
}

func init() { proto.RegisterFile("api-pb/types.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 374 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xcf, 0x4e, 0xea, 0x40,
	0x14, 0xc6, 0x53, 0x2e, 0xe5, 0xc2, 0xe9, 0x05, 0x2e, 0x03, 0x1a, 0xd2, 0x98, 0x48, 0x26, 0x31,
	0x21, 0x04, 0x69, 0xc4, 0x1d, 0x3b, 0x13, 0xff, 0x6c, 0x74, 0x53, 0xe3, 0x03, 0x4c, 0xe9, 0xb1,
	0x69, 0xc4, 0xce, 0xd8, 0x19, 0x34, 0x6e, 0x7d, 0x05, 0x1f, 0xcd, 0x57, 0xf0, 0x09, 0x7c, 0x02,
	0x33, 0xd3, 0xb1, 0x29, 0x6c, 0x64, 0x37, 0xe7, 0xcc, 0xf7, 0xfd, 0xce, 0x9c, 0xaf, 0x05, 0xc2,
	0x44, 0x7a, 0x2c, 0xa2, 0x40, 0xbd, 0x0a, 0x94, 0x33, 0x91, 0x73, 0xc5, 0x89, 0xcb, 0x44, 0x2a,
	0x22, 0xff, 0x20, 0xe1, 0x3c, 0x59, 0x61, 0xc0, 0x44, 0x1a, 0xb0, 0x2c, 0xe3, 0x8a, 0xa9, 0x94,
	0x67, 0x56, 0xe4, 0x8f, 0xec, 0xad, 0xa9, 0xa2, 0xf5, 0x7d, 0x10, 0xa3, 0x5c, 0xe6, 0xa9, 0x50,
	0x3c, 0x2f, 0x14, 0x74, 0x0a, 0xf5, 0x3b, 0x89, 0x39, 0x21, 0x50, 0xcf, 0xd8, 0x23, 0x0e, 0x9d,
	0x91, 0x33, 0x6e, 0x85, 0xe6, 0x4c, 0xfe, 0xc3, 0x1f, 0x96, 0xe0, 0xb0, 0x36, 0x72, 0xc6, 0x6e,
	0xa8, 0x8f, 0xf4, 0x04, 0x3a, 0x67, 0x71, 0xac, 0x0d, 0x21, 0x3e, 0xad, 0x51, 0x2a, 0x72, 0x08,
	0xf5, 0xb5, 0xc4, 0xdc, 0xf8, 0xbc, 0xb9, 0x37, 0x33, 0xaf, 0x9a, 0x19, 0x85, 0xb9, 0xa0, 0x3d,
	0xe8, 0x96, 0x16, 0x29, 0x78, 0x26, 0x91, 0x4e, 0xa1, 0x73, 0x85, 0xaa, 0x4a, 0xf1, 0xa1, 0xa9,
	0xc5, 0x95, 0x17, 0x94, 0x35, 0x9d, 0x43, 0xb7, 0x54, 0x17, 0x80, 0xdf, 0x87, 0x5e, 0xc2, 0xbf,
	0x6b, 0x9e, 0xa4, 0xd9, 0x0e, 0x7c, 0x7d, 0x27, 0x98, 0x94, 0x2f, 0x3c, 0x8f, 0xcd, 0xaa, 0xad,
	0xb0, 0xac, 0xe9, 0x11, 0xb4, 0x2d, 0xc7, 0x4e, 0x1e, 0x80, 0xab, 0xf8, 0x03, 0x66, 0x96, 0x52,
	0x14, 0x34, 0x80, 0xde, 0x39, 0xae, 0x50, 0xe1, 0xae, 0x3b, 0x0d, 0x80, 0x54, 0x0d, 0x05, 0x7c,
	0xfe, 0xe5, 0x80, 0xa7, 0x1b, 0xb7, 0x98, 0x3f, 0xa7, 0x4b, 0x24, 0x37, 0xf0, 0xd7, 0x46, 0x47,
	0xf6, 0xec, 0x8e, 0x9b, 0xe9, 0xfb, 0xfb, 0xdb, 0x6d, 0x9b, 0x70, 0xff, 0xed, 0xe3, 0xf3, 0xbd,
	0xd6, 0xa6, 0xcd, 0x80, 0xc5, 0xb1, 0x9e, 0xba, 0x70, 0x26, 0x1a, 0x67, 0x83, 0x2c, 0x71, 0x9b,
	0x9f, 0xa1, 0xc4, 0x6d, 0xe5, 0x5d, 0xc1, 0x25, 0xa8, 0x7e, 0x70, 0x17, 0xe0, 0x9a, 0x6c, 0x48,
	0xdf, 0xba, 0xaa, 0x89, 0xfb, 0x83, 0xcd, 0xa6, 0x05, 0xf5, 0x0c, 0xc8, 0xa3, 0x8d, 0x60, 0xa5,
	0xfb, 0x0b, 0x67, 0x12, 0x35, 0xcc, 0x7f, 0x78, 0xfa, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xa5, 0x23,
	0xff, 0x92, 0xe4, 0x02, 0x00, 0x00,
}
